### ISSUE TITLE
Don't trigger review for pr mentions

### ISSUE THREAD

**Issue by mdbitz** [Automattic/vip-go-ci#61] opened 2019-09-06 13:12 UTC
Example https://github.com/wpcomvip/cbs-local/pull/237 
When I create off-shoots for Preprod and Staging to be merged in as separate pull requests and mention the original pull request - that prompts the bot to do another review. 
Can we please kick that?

**Comment by gudmdharalds** [comment] 2019-12-17 18:30
I'm not able to reproduce this. I tried that in https://github.com/wpcomvip/vip-test/pull/164 and https://github.com/wpcomvip/vip-test/pull/166 but had no success. Closing.

**Closed** 2019-12-17 18:30 UTC
